# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: EB Corbos Linux for Safety Applications - Build & Test

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'integration/**'
  merge_group:
    types: [checks_requested]
    paths:
      - 'integration/**'

jobs:
  build:
    name: aarch64
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eclipse-score/devcontainer:v1.1.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build for EB corbos Linux for Safety Applications and run tests
        run: |
          bazel build --config=eb-aarch64 //images/ebclfsa_aarch64/scrample_integration:run
        working-directory: ./integration

      - name: Upload test logs
        uses: actions/upload-artifact@v5
        with:
          name: test-logs
          path: |
            ebclfsa/bazel-bin/scrample_integration/*.log
